services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - .:/app:z
      - staticfiles:/app/staticfiles
    ports:
      - "13000:8000"  # Host tarafını 12000 yaptım, 11000 yerine
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
      - redis
      - rabbitmq
    command: /start.sh
    networks:
      - banker_local_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - banker_local_db:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - banker_local_nw

  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - staticfiles:/app/staticfiles
      - logs_store:/var/log/nginx
    depends_on:
      - api
    networks:
      - banker_local_nw

  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - banker_mailpit_db:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_MAX_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - banker_local_nw

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    networks:
      - banker_local_nw

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - banker_local_nw

  celeryworker:
    <<: *api
    command: /start-celeryworker.sh
    ports: []

  flower:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    entrypoint: /start-flower.sh   # ÖNEMLİ: Django entrypointini override ediyor
    ports:
      - "5555:5555"
    volumes:
      - flower_db:/app/flower-db
    env_file:
      - ./.envs/.env.local
    depends_on:
      - rabbitmq
      - redis
    networks:
      - banker_local_nw

  celerybeat:
    <<: *api
    command: /start-celerybeat.sh
    ports: []

networks:
  banker_local_nw:
    external: false  # internal network oluşturacak, sistemde yoksa sorun çıkmaz

volumes:
  banker_local_db:
  banker_mailpit_db:
  staticfiles:
  logs_store:
  rabbitmq_data:
  rabbitmq_log:
  flower_db: